version: 4.4.{build}
branches:
  only:
    - master
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2022
clone_depth: 1
build_script:
- cmd: Src\Setup\__MakeFinal.bat
test: off
only_commits:
  files:
    - Src/
    - Localization/
deploy:
- provider: GitHub
  tag: v$(APPVEYOR_BUILD_VERSION)
  release: $(APPVEYOR_BUILD_VERSION)
  on:
    APPVEYOR_ACCOUNT_NAME: passionate-coder
  auth_token:
    secure: SOu6Y71k0oIxXJR35x+7ZeU/+WRW8kaGnCWcbR3OVOd8HeCJwB1Tw3hUJa5EveLGKaGoMKGqAh01Pwc8tWX4xmphZsYYUr09IVjA0+rqgN5VT87CXD6OQxUxBJ7g+9IN
  prerelease: true
